### ISSUE TITLE
Rector SetList::NAMING with Symfony Autowiring by type and name

### ISSUE THREAD

**Issue by 94noni** [rectorphp/rector-symfony#100]
Ref https://symfony.com/blog/new-in-symfony-4-2-autowiring-by-type-and-name

---

### Issue

I do have this config on my Symfony config file:

```yaml
# config/services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $env: '%kernel.debug%'
            $stateMachinePurchaseOrder: '@state_machine.purchase_order'
```

In a php class as service constructor:

```php
    public function __construct(private readonly StateMachine $stateMachinePurchaseOrder, ...) {...}
```

With rector `SetList::NAMING`:

```diff
- private readonly StateMachine $stateMachinePurchaseOrder
+ private readonly StateMachine $stateMachine
```

and thus it breaks the autowiring of Symfony services binded via name

---

### Question

Is it possible in some way to configure/exclude/other this to not be "fixed"?

Thank you
