### ISSUE TITLE
GetToConstructorInjectionRector

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector-symfony#225]
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.13.10 (invoke `vendor/bin/rector --version`)             |

Current behaviour of GetToConstructorInjectionRector is that it creates a property name from the service's class name. When we refactor a controller that fetches from container two different services but they are of the same type we break the app.

```php
class MyServiceClass {
    public function __construct(string $value)
    {
    }
}

class MyController
{
    public function firstAction()
    {
        $service = $this->get('app.service.my_service_class_v1');
    }
    
    public function secondAction()
    {
        $service = $this->get('app.service.my_service_class_v2');
    }
}
```
```yml
services:
  app.service.my_service_class_v1:
    class: MyServiceClass
    arguments: ['someValue']

  app.service.my_service_class_v2:
    class: MyServiceClass
    arguments: ['otherValue']
```

After running GetToConstructorInjectionRector we end up with:
```php
class MyController
{
    private MyServiceClass $myServiceClass;    

    public function __construct(MyServiceClass $myServiceClass)
    {
        $this->myServiceClass = $myServiceClass;
    }

    public function firstAction()
    {
        $service = $this->myServiceClass;
    }
    
    public function secondAction()
    {
        $service = $this->myServiceClass;
    }
```

## Expected Behaviour

There should be created two separate class properties.
