### ISSUE TITLE
AddRouteAnnotationRector does not consider null in default route param value

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector-symfony#242]
| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.10            |

Consider this example:
Yaml:
```yaml
route_name:
  path: /some-path/{routeParam}
  defaults: { _controller: 'MyBundle:Customer:edit', routeParam: null }
```
PHP:
```php
    public function editAction($routeParam = null)
    {
    }
```
AddRouteAnnotationRector results in 
```php
    /**
     * @Route(path="some-path/{routeParam}", name="route_name", defaults={"routeParam"=})
     */
    public function editAction($routeParam = null)
    {
    }
```
In the yaml notation we have `routeParam: null` (`routeParam: ~` behaves the same) and in annotation we have `defaults={"routeParam"=})`.
