### ISSUE TITLE
AddRouteAnnotationRector does not add multiple @Route

### ISSUE THREAD

**Issue by javaDeveloperKid** [rectorphp/rector-symfony#244]
Consider this example:
```yaml
route_name:
  path: /some-path
  defaults: { _controller: 'MyBundle:Customer:edit' }

route_name_2:
  path: /some-path # same path
  defaults: { _controller: 'MyBundle:Customer:edit' } # same defaults
```
AddRouteAnnotationRector results in
```php
    /**
     * @Route(path="some-path", name="route_name")
     */
    public function editAction()
    {
    }
```
AddRouteAnnotationRector should add two `@Route` annotations.
