### ISSUE TITLE
AddRouteAnnotationRector does not work with invokable Controller

### ISSUE THREAD

**Issue by jambonfarci** [rectorphp/rector-symfony#301]
## Minimal YAML Code Causing Issue

```yaml
test_route:
  path: /test
  methods: ["GET"]
  controller: App\Controller\TestRouteController
```

## Minimal PHP Code Causing Issue

```php
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TestRouteController extends AbstractController
{
    public function __invoke(): void {
    }
}
```

### Responsible Rule

+ `AddRouteAnnotationRector`

## Expected Behaviour

```diff
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
+use Symfony\Component\Routing\Annotation\Route;

class TestRouteController extends AbstractController
{
+   /**
+   * @Route(path="/test", name="test_route", methods={"GET"})
+   */
    public function __invoke(): void {
    }
}
```
