### ISSUE TITLE
AddRouteAnnotationRector ignore prefix on resource files

### ISSUE THREAD

**Issue by TeLiXj** [rectorphp/rector-symfony#354]
I've started the migration of a very old Symfony 2.3 project and it have a `routing.yml` file to import other files.
From a YAML like this
```yaml
api_public_webservice:
    resource: "routing_api_public_webservice.yml"
    prefix: /api-public
```
the result is (after apply annotations to routes rule too)
```php
#[Route("/webservice", name: "api_public_webservice")]
```
because in recent Symfony versions (in my case 4.4) the files in the `routes` directory are loaded automatically without see the content of the `routing.yml` file.
I don't know if this could be relevant or not, but could happend in other cases.
